name: ci-test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6' # Use the exact Go version from your go.mod file
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
