name: ci-test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to v4
        with:
          submodules: 'recursive'

      - name: Set up Go
        uses: actions/setup-go@v5 # Update to v5 or later
        with:
          go-version: '1.20'
        id: go

      - name: Test
        run: make test
